#python run_training_vc2.py \
    #--result-dir /project/xqzhu_dis/repo_results/stylegan2/results_vc2_byvae_celeba \
    #--data-dir /project/xqzhu/Datasets/CelebA_dataset \
    #--dataset celeba_tfr \
    #--config config-c \
    #--arch orig \
    #--metrics fid50k,tpl \
    #--num-gpus 2 \
    #--model_type vc2_gan_byvae \
    #--C_lambda 0.1 \
    #--fmap_decay 1 \
    #--epsilon_loss 3 \
    #--random_seed 1000 \
    #--random_eps True \
    #--latent_type normal \
    #--delta_type onedim \
    #--gamma 100 \
    #--batch_size 32 \
    #--batch_per_gpu 16 \
    #--n_samples_per 7 \
    #--return_atts True \
    #--I_fmap_base 9 \
    #--G_fmap_base 10 \
    #--G_nf_scale 6 \
    #--D_fmap_base 9 \
    #--fmap_min 64 \
    #--fmap_max 512 \
    #--topk_dims_to_show -1 \
    #--latent_split_ls_for_std_gen [2,2,2,2,2,2,2,2,2,2,2,2] \
    #--module_list '[STD_gen_sp-4-24]'

#CUDA_VISIBLE_DEVICES=2,3 \
    #python run_training_vc2.py \
    #--result-dir /project/xqzhu_dis/repo_results/stylegan2/results_vc2_byvae_celeba \
    #--data-dir /project/xqzhu/Datasets/CelebA_dataset \
    #--dataset celeba_tfr \
    #--resume_pkl /project/xqzhu_dis/repo_results/stylegan2/results_vc2_byvae_celeba/00020-vc2_gan_byvae-celeba_tfr-2gpu-config-c/network-snapshot-000361.pkl \
    #--config config-c \
    #--metrics fid50k,tpl \
    #--num-gpus 2 \
    #--model_type vc2_gan_byvae \
    #--C_lambda 0.1 \
    #--fmap_decay 1 \
    #--epsilon_loss 3 \
    #--random_seed 1000 \
    #--random_eps True \
    #--latent_type normal \
    #--delta_type onedim \
    #--gamma 100 \
    #--batch_size 32 \
    #--batch_per_gpu 16 \
    #--n_samples_per 7 \
    #--return_atts True \
    #--I_fmap_base 9 \
    #--G_fmap_base 10 \
    #--G_nf_scale 6 \
    #--D_fmap_base 9 \
    #--fmap_min 64 \
    #--fmap_max 512 \
    #--topk_dims_to_show -1 \
    #--latent_split_ls_for_std_gen [2,2,2,2,2,2,2,2,2,2] \
    #--module_list '[PG_gen_sp-6-20]'

CUDA_VISIBLE_DEVICES=2,3 \
    python run_training_vc2.py \
    --result-dir /project/xqzhu_dis/repo_results/stylegan2/results_vc2_byvae_clevrSim_byvae \
    --data-dir /project/xqzhu_dis/Datasets/CLEVR_disentangle \
    --dataset clevr_simple \
    --config config-c \
    --metrics fid50k,tpl \
    --num-gpus 2 \
    --model_type vc2_gan_byvae \
    --C_lambda 0.01 \
    --fmap_decay 1 \
    --epsilon_loss 3 \
    --random_seed 1000 \
    --random_eps True \
    --latent_type normal \
    --delta_type onedim \
    --gamma 100 \
    --batch_size 8 \
    --batch_per_gpu 4 \
    --n_samples_per 7 \
    --return_atts True \
    --I_fmap_base 9 \
    --G_fmap_base 8 \
    --G_nf_scale 6 \
    --D_fmap_base 9 \
    --fmap_min 64 \
    --fmap_max 512 \
    --topk_dims_to_show -1 \
    --module_list '[Const-512, ResConv-up-1, C_spgroup-1-3, ResConv-id-1, Noise-2, ResConv-up-1, C_spgroup-1-3, ResConv-id-1, Noise-2, ResConv-up-1, C_spgroup-1-3, ResConv-id-1, Noise-2, ResConv-up-1, C_spgroup-1-3, ResConv-id-1, Noise-2, ResConv-up-1, ResConv-id-1, ResConv-up-1, ResConv-id-2]'
